apiVersion: v2
name: lnd
version: 0.11.1-dev
appVersion: 0.19.3
description: LND helm chart
keywords:
  - lnd
maintainers:
  - name: Blink Devs
    email: dev@blink.sv
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 18.1.15
    condition: postgresql.enabled
  - name: lndmon
    version: x.x.x
    condition: lndmon.enabled
