#@data/values
---
deployments_git_uri: git@github.com:blinkbitcoin/blink-deployments.git
deployments_git_branch: main
git_lnd_sidecar_bot_branch: bot-bump-lnd-sidecar-image
git_lnd_backup_bot_branch: bot-bump-lnd-backup-image
git_mongo_backup_bot_branch: bot-bump-mongo-backup-image
git_kafka_connect_bot_branch: bot-bump-kafka-connect-image
git_org_uri: git@github.com:blinkbitcoin
git_uri: git@github.com:blinkbitcoin/charts.git
git_branch: main
gates_branch: cepler-gates
github_private_key: ((github-blinkbitcoin.private_key))
github_token: ((github-blinkbitcoin.api_token))
github_app_id: ((github-blinkbitcoin.github_app_id))
github_app_private_key: ((github-blinkbitcoin.github_app_private_key))
docker_registry: us.gcr.io/galoy-org
docker_registry_user: ((docker-creds.username))
docker_registry_password: ((docker-creds.password))
testflight_backups_creds: ((testflight-backups-bucket.creds_json))
testflight_okex_secret_key: ((testflight-okex.secret_key))
testflight_okex_passphrase: ((testflight-okex.passphrase))
testflight_okex_api_key: ((testflight-okex.api_key))
testflight_galoy_api_key: ((testflight-stablesats.galoy_api_key))
staging_worker_tag: galoy-staging
staging_smoketest_kubeconfig: ((staging-smoketest.kubeconfig))
staging_state_bucket: "galoy-staging-tf-state"
staging_creds: ((staging-gcp-creds.creds_json))

galoy_slack_webhook_url: ((galoy-main-slack.api_url))
monitoring_slack_webhook_url: ((monitoring-slack.api_url))
bitcoin_slack_webhook_url: ((bitcoin-slack.api_url))
addons_slack_webhook_url: ((addons-slack.api_url))
auth_slack_webhook_url: ((auth-slack.api_url))
stablesats_slack_webhook_url: ((addons-slack.api_url))
galoy_deps_slack_webhook_url: ((galoy-deps-slack.api_url))
slack_username: concourse
